Protocol Events of SAMR
=======================

## Authentication

### auth (C2S)

`<String> // Base64 encoded client proof`

Client requests authentication and providing a `proof` as Base64-encoded string
as a single argument.

A proof is generated by client side using the `Authenticator.js`. It's a custom
protocol containing a claim and a cert, signed with client's PGP private key,
and shipped together with client's PGP public key to server. The user's claim
contains a timestamp, a connection id, and optionally an existing session id.
The cert is issued by an authority PGP key in cleartext. The server will
validate that both the user's self signature and the authorizing cert being
valid.

By authentication, the client requests binding the current connection with a new
or existing session. If an existing session at server using given session_id is
found, it must be validated for having been created for the same client cert ID
as the one present in current authentication request.



### auth.success (S2C)

`{
    session_id: <String>, // a new session UUID associated with this connection
}`

Fired once an event of `auth` is executed successfully. Session at server side
is created or newed.

### auth.failure (S2C)

`
{
    reason: <String>, // description of the failure condition
}
`

Fired when authentication failed, or server found the session being invalid
later. The session and all associated data might have been deleted at server
side, and the client should create a new session.
